# --- QMIX specific parameters ---

# use epsilon greedy action selector
action_selector: "epsilon_greedy"
epsilon_start: 1.0
epsilon_finish: 0.05
epsilon_anneal_time: 50

runner: "parallel"
batch_size_run: 8

buffer_size: 5000

# update the target network every {} episodes
target_update_interval: 200

# use the Q_Learner to train
agent_output_type: "q"
learner: "latent_q_learner"
double_q: True
mixer: "qmix"
mixing_embed_dim: 32

# for latent model
name: "qmix_smac_latent_parallel"

agent: "latent_rnn"
mac: "separate_mac"

latent_dim: 2
#entropy_loss_weight : 1.0
#ce_loss_weight: 1e-4
kl_loss_weight: 1e-4
h_loss_weight: 1e-6
#hg_dim: 16
NN_HIDDEN_SIZE: 12
dis_loss_weight: 1e-2
#dis_cur: True
#dis_net: True
dis_time: 5000000
dis_sigmoid: False

#evolve_balance: 0.999
#snail_max_t: 128
#snail_key_size: 8
#snail_value_size: 8
#snail_filters: 8

use_tensorboard: True
save_model: True
use_cuda: False
device_num: 0
save_replay: False