env: gather_and_defend

env_args:
  n_agents: 10
  n_enemies: 2
  episode_limit: 200
  move_amount: 1
  continuing_episode: False
  obs_all_health: True
  obs_enemy_health: True
  obs_own_health: True
  obs_last_action: False
  obs_pathing_grid: False
  obs_terrain_height: False
  obs_instead_of_state: False
  obs_timestep_number: False
  state_last_action: True
  state_timestep_number: False
  reward_sparse: False
  reward_only_positive: True
  reward_death_value: 0.5
  reward_win: 5
  reward_defeat: 0.01
  reward_integrate: 20
  reward_gather: 2
  reward_negative_scale: 0.5
  reward_scale: True
  reward_scale_rate: 20
  debug: False
  sight_range: 9
  shoot_range: 1
  map_x: 10
  map_y: 10
  agent_health: 10
  enemy_health: 10
  agent_attack: 5
  enemy_attack: 2
  base_health: 150
  n_resources: 2


learner_log_interval: 20000
log_interval: 20000
runner_log_interval: 20000
t_max: 10050000
test_interval: 20000
test_nepisode: 24
test_greedy: True